# Generated by Django 4.2 on 2023-04-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0003_mangaseriesmodel_delete_filemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangaseriesmodel',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mangaseriesmodel',
            name='chapter_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Chapters'),
        ),
        migrations.AlterField(
            model_name='mangaseriesmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mangaseriesmodel',
            name='volume_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Volumes'),
        ),
    ]
