# Generated by Django 4.2 on 2023-04-06 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0004_alter_mangaseriesmodel_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaVolumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('thumbnail', models.FileField(null=True, upload_to='')),
                ('volume', models.IntegerField(null=True)),
                ('chapter', models.IntegerField(null=True)),
                ('page_total', models.IntegerField(verbose_name='Total Pages')),
                ('page_current', models.IntegerField(verbose_name=0)),
                ('manga_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filemanager.mangaseriesmodel')),
            ],
            options={
                'ordering': ['volume'],
            },
        ),
    ]
