# Generated by Django 4.2 on 2023-04-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0005_mangavolumemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangavolumemodel',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
