# Generated by Django 4.2 on 2023-04-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0006_alter_mangavolumemodel_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangavolumemodel',
            name='page_current',
            field=models.IntegerField(default=0),
        ),
    ]
